### ISSUE TITLE
Shouldn't generate both of static and non-static method with the same name for pybind11

### ISSUE THREAD

**Issue by jslee02** [personalrobotics/chimera#262]
`pybind11` doesn't allow this: runtime error. I haven't tested this for Boost.Python.

**Comment by jslee02** [comment]
Here are some observations:

With the following C++ code:
```cpp
namespace test1 {

class Integer {
public:
    Integer(int val) : m_val(oval) {}
    int add(int a) {
        return a + m_val;
    }
    static int add(int a, int b) {
        return a + b;
    }
private:
    int m_val;
};

} // namespace test1
```
chimera generates the following bindings for Boost.Python and pybind11:
```cpp
    // Boost.Python
    ::boost::python::object parent_object(::boost::python::scope().attr("test1"));
    ::boost::python::scope parent_scope(parent_object);
    ::boost::python::class_<chimera_test::test1::Integer, ::boost::noncopyable >("Integer", boost::python::no_init)
        .def("__init__", ::boost::python::make_constructor(+[](int val) -> chimera_test::test1::Integer * { return new chimera_test::test1::Integer(val); }, ::boost::python::default_call_policies(), (::boost::python::arg("val"))))
        .def("add", +[](chimera_test::test1::Integer *self, int a) -> int { return self->add(a); }, (::boost::python::arg("a")))
        .def("add", +[](int a, int b) -> int { return chimera_test::test1::Integer::add(a, b); }, (::boost::python::arg("a"), ::boost::python::arg("b")));

    // pybind11
    auto sm = m.def_submodule("test1");
    auto attr = sm;
    ::pybind11::class_<chimera_test::test1::Integer >(attr, "Integer")

        .def(::pybind11::init<int>(), ::pybind11::arg("val"))
        .def("add", +[](chimera_test::test1::Integer *self, int a) -> int { return self->add(a); }, ::pybind11::arg("a"))
        .def_static("add", +[](int a, int b) -> int { return chimera_test::test1::Integer::add(a, b); }, ::pybind11::arg("a"), ::pybind11::arg("b"));
```

Bindings generated by Boost.Python seems to work as
```python
>>> import class_boost_python as boost
>>> boost.test1.Integer.add(1, 2)
3
>>> i = boost.test1.Integer(1)
>>> i.add(2)
3
>>> 
```
but `add(int, int)` doesn't seem to be regarded as static method because following code doesn't work as:
```python
>>> i.add(1, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Boost.Python.ArgumentError: Python argument types in
    Integer.add(Integer, int, int)
did not match C++ signature:
    add(int a, int b)
    add(chimera_test::test1::Integer*, int a)
```
`help()` also says that as
```python
>>> help(boost.test1.Integer)
Help on class Integer in module class_boost_python.test1:

class Integer(Boost.Python.instance)
 |  Method resolution order:
 |      Integer
 |      Boost.Python.instance
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(...)
 |      __init__( (object)arg1, (int)val) -> object
 |  
 |  __reduce__ = <unnamed Boost.Python function>(...)
 |  
 |  add(...)
 |      add( (Integer)arg1, (int)a) -> int
 |      
 |      add( (int)a, (int)b) -> int
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from Boost.Python.instance:
 |  
 |  __new__(*args, **kwargs) from Boost.Python.class
 |      Create and return a new object.  See help(type) for accurate signature.
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from Boost.Python.instance:
 |  
 |  __dict__
 |  
 |  __weakref__
```

Bindings generated by pybind11 results in import error as
```python
>>> import class_pybind11 as p11
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: overloading a method with both static and instance methods is not supported; error while attempting to bind static method Integer.add(a: int, b: int) -> int
```

If we use a different name for the static method as `add_static`, pybind11 bindings works as
```python
>>> py11.test1.Integer.add_static(1, 2)
3
>>> i = py11.test1.Integer(1)
>>> i.add(2)
3
>>> i.add_static(1, 2)
3
>>> help(py11.test1.Integer)
Help on class Integer in module class_pybind11.test1:

class Integer(pybind11_builtins.pybind11_object)
 |  Method resolution order:
 |      Integer
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(...)
 |      __init__(self: class_pybind11.test1.Integer, val: int) -> None
 |  
 |  add(...)
 |      add(self: class_pybind11.test1.Integer, a: int) -> int
 |  
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |  
 |  add_static(...) from builtins.PyCapsule
 |      add_static(a: int, b: int) -> int
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from pybind11_builtins.pybind11_object:
 |  
 |  __new__(*args, **kwargs) from pybind11_builtins.pybind11_type
 |      Create and return a new object.  See help(type) for accurate signature.
```
